learndjango/learndjango/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url('', include('polls.urls')),
]

learndjango/polls/urls.py
from django.conf.urls import url
from polls import views

app_name = 'polls'
urlpatterns = [
    url('^$',views.IndexView.as_view(), name='index'),
    url('^question/add/$', views.AddQuestion.as_view(), name='add-question'),
    url('^question/add/$', views.Add_1.as_view(), name='add'),
    url('(?P<question_id>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url('(?P<question_id>[0-9]+)/add-choice/$', views.AddChoice.as_view(), name='add-choice'),
    url('(?P<question_id>[0-9]+)/choice_a/$', views.choice_example.as_view(), name='choice_a'),
    url('(?P<question_id>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url('(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    #url('(?P<question_id>[0-9]+)/choice_student/$', views.Add_Choice_Student.as_view(), name='choice_student'),

]

learndjango/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
from ttk import Entry

from django.db import models

# Create your models here.
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length= 200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return  self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    choice_text= models.CharField(max_length= 200)
    votes= models.IntegerField(default=0)


    def __str__(self):
        return self.choice_text
def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

'''
class Student(models.Model):
    FRESHMAN = 'FR'
    SOPHOMORE = 'SO'
    JUNIOR = 'JR'
    SENIOR = 'SR'
    YEAR_IN_SCHOOL_CHOICES = (
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
    )
    year_in_school = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )

    def is_upperclass(self):
        return self.year_in_school in (self.JUNIOR, self.SENIOR)
'''

learndjango/polls/forms.py
from django import forms

from polls.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text','pub_date']

learndjango/polls/views.py
# -*- coding: utf-8 -*-
import datetime
from audioop import reverse

from django.http import HttpResponse, HttpResponseRedirect, Http404

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.generic import CreateView

from polls.models import Question, Choice

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

#=========================#

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

#=========================#

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

#=========================#


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

    def get_context_data(self, **kwargs):
        context = generic.ListView.get_context_data(self, **kwargs)

        question_ids = Choice.objects.filter(votes__gt = 5).values_list('question_id', flat=True)
        context['questions'] = Question.objects.filter(id__in=question_ids)
        # context['questions'] = Question.objects.filter(choice__votes__gte=5)

                                    #===========#

        question_id1 = Choice.objects.filter(votes__lt = 6).values_list('question_id', flat=True)
        context['question_example'] = Question.objects.filter(id__in=question_id1)
        #context['question_example'] = Question.objects.filter(choice__votes__lt= 6)
                                    #===========#

        #context['questions'] = Question.objects.filter(pub_date__gt=datetime.datetime.now())
        context['question_pub_date'] = Question.objects.filter(pub_date__year = 2005)

        #=============== Delete object ==============

        Question.objects.filter(question_text = 'QƯE').delete()
        Choice.objects.filter(choice_text = 'dasd').delete()

        return context



class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    template_name = 'polls/results.html'
    model = Question

    pk_url_kwarg = 'question_id'


def get_queryset(self):
    """
    Return the last five published questions (not including those set to be
    published in the future).
    """
    return Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    template_name = 'polls/detail.html'
    context_object_name = 'question'

    def get_object(self, queryset=None):
        return Question.objects.get(pk=self.kwargs['question_id'])


# =========================#


class AddQuestion(CreateView):
    model = Question
    fields = ['question_text','pub_date']
    template_name = 'polls/addquestion.html'

    def get_success_url(self):
        return reverse('polls:index')

class Add_1(CreateView):
    model = Question
    fields = ['question','pub_date']
    template_name = 'polls/add.html'

    def get_success_url(self):                    # The URL to redirect to when the form is successfully processed.
        return reverse('polls:index')             # Returns success_url by default.


class AddChoice(CreateView):
    model = Choice
    fields = ['choice_text']
    template_name = 'polls/addchoice.html'


    def form_valid(self, form):
        choice = form.save(False)
        choice.question_id = self.kwargs['question_id']
        choice.save()
        return HttpResponseRedirect(reverse('polls:detail', kwargs={'question_id':choice.question_id}))


class choice_example(CreateView):
    model = Choice
    fields = ['choice_text']
    template_name= 'polls/choice.html'

    def form_valid(self, form):                                     # Redirects to get_success_url().
        choice= form.save(False)                                    # not save in database.
        choice.question_id = self.kwargs['question_id']             # "self.kwagrs" to access the url parameters in class based view.
        choice.save()
        return HttpResponseRedirect(reverse('polls:detail', kwargs={'question_id':choice.question_id}))

'''
class Add_Choice_Student(CreateView):
    model = Student
    template_name = 'polls/Choice_student.html'

    def form_valid(self, form):
        Student= form.save(False)
        Student.question_id= self.kwargs['question_id']
        Student.save()
        return HttpResponseRedirect(reverse('polls:detail',kwargs={'question_id': Student.question_id}))
'''

learndjango/templates/polls/Choice_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   <form action="." method="post"> {% csrf_token %}
        {{ form.as_p }}
       <input type="submit" value="Submit">
    </form>
</body>
</html>

learndjango/templates/polls/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   <form action="{%  url 'polls:add' %}" method="post"> {% csrf_token %}
        {{ form.as_p }}
       <input type="submit" value="Submit">
    </form>
</body>
</html>

learndjango/templates/polls/addchoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   <form action="." method="post"> {% csrf_token %}
        {{ form.as_p }}
       <input type="submit" value="Submit">
    </form>
</body>
</html>

learndjango/templates/polls/addquestion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   <form action="{%  url 'polls:add-question' %}" method="post"> {% csrf_token %}
        {{ form.as_p }}
       <input type="submit" value="Submit">
    </form>
</body>
</html>

learndjango/templates/polls/choice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
       <form action="." method="post"> {% csrf_token %}
        {{ form.as_p }}
       <input type="submit" value="Submit">
    </form>
</body>
</html>

learndjango/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
    <a href="{%  url 'polls:add-choice' question.id %}">
        add choise.
    </a><br>
    <a href="{% url 'polls:choice_a' question.id %}">
        Choice.
    </a><br>
</form>

learndjango/templates/polls/index.html
<h1>Question:</h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
{% endif %}
<br>
  <a href="{%  url 'polls:add-question' %}">
      Add question
  </a><br>
      <a href="{%  url 'polls:add' %}">
      Add
  </a><br>
</p>
<h1>Filter question:</h1>
 {% for question in questions %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}

<h1>Filter question example :</h1>
 {% for question in question_example %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}

<h1>Filter pub_date :</h1>
 {% for question in question_pub_date %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}

learndjango/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>